### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by willer94** [amyxlase/relpose-plus-plus#1]
Because all zip files of CO3Dv2 occupy 5.5 TB of disk-space, it is difficult to follow this work if all file are used. I am wonder if you only used the single-sequence subset, which takes takes 8.9 GB.

**Comment by amyxlase** [comment]
We used a subset of each category, specified by `set_lists_fewview_dev.json`. This occupies about 300GB of disk space. The script we used to filter out this subset from each category can be found here at`preprocess/preprocess_co3d.py`.

**Comment by ttsesm** [comment]
@amyxlase, @jasonyzhang how do I download only the 300GB subset of the CO3D dataset? Do I need to download all the dataset and run the `preprocess/preprocess_co3d.py` script or there is another way to do it?

**Comment by jasonyzhang** [comment]
[Here is a link](https://drive.google.com/file/d/12cEWQ0IgsuvlOWjxHxreWqB4v-2zYnue/view?usp=sharing) to the subset of images and pre-processed annotations of CO3D data that we used. The total size should be 277GB.

Please note that by using this data, you agree to abide by the licensing agreement provided by [CO3D](https://github.com/facebookresearch/co3d)

**Comment by zelingao98** [comment]
Hi jasonyzhang!
Thank you for amazing work! @jasonyzhang 
I am currently using relpose and I also want to download your preprocessed data.
But unfortunately there is a bug caused by google drive (I mean it is a common issue for google drive😭).

<img width="1132" alt="image" src="https://github.com/amyxlase/relpose-plus-plus/assets/119651008/35ed60b0-8eac-4f49-865c-51a03bfdbfdb">

So could you share your processed data using some alternative ways? I would really appreciate your work and your shared data!

**Comment by jasonyzhang** [comment]
Can you try downloading it from the browser? Sometimes downloading from the command line gets throttled.

**Comment by zelingao98** [comment]
Thank you for your replying!!! @jasonyzhang 

I try to download it from the browser and it can also be interrupted for some unknown reasons😭. Do you have any idea about this.

Best,
Kuma

**Comment by zelingao98** [comment]
> 

maybe I should @google here, LOL😂

**Comment by jasonyzhang** [comment]
Sorry, I just saw this. Are you still trying to download the dataset?

**Comment by AdamBethell** [comment]
Hi @jasonyzhang, I am also trying to download the dataset and it also keeps getting interrupted or I sometimes get the message: 

"Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

Do you have any idea why this is happening and is there any other way of sharing the data?

**Comment by jasonyzhang** [comment]
It seems that us re-hosting CO3D is no longer a sustainable solution. Could you re-direct issues with downloading the dataset to the CO3D maintainers? Maybe they can re-host a subset with just the images.
