### ISSUE TITLE
How to determine the Intrinsic parameters for NeRS

### ISSUE THREAD

**Issue by ZhenhuiL1n** [amyxlase/relpose-plus-plus#11]
Hi, 

it is a very excellent project and I have one small question. 

In your evaluation, how to set the intrinsic parameters for the NeRS to reconstruct the whole scene?

Thanks a lot!

**Comment by jasonyzhang** [comment]
Since our method doesn't predict intrinsics, we used the default intrinsics initialization that NeRS uses (fov of 60 degrees). Of course, if the actual intrinsics of the scene are known, those should be used as the initialization
