### ISSUE TITLE
robot.html doesn't show image for each camera in render, does this mean the demo didn't work?

### ISSUE THREAD

**Issue by hadillivvy** [amyxlase/relpose-plus-plus#14]
I ran the following in the terminal and the script finished with no errors and the output is a robot.html:
`python relpose/demo.py  --image_dir examples/robot/images \
    --mask_dir examples/robot/masks --output_path robot.html
`

When I open the robot.html in the browser, I see a number of cameras but there's no image associated with each one. Is this normal?
![Screenshot from 2023-12-19 15-09-55](https://github.com/amyxlase/relpose-plus-plus/assets/150967838/fe007dc3-62e0-4560-b943-552986cffee0)

**Comment by jasonyzhang** [comment]
You should be able to see the original images, similar to here: https://amyxlase.github.io/relpose-plus-plus/robot.html

If you can't seem them, maybe try checking if the image was embedded in the HTML file properly
