### ISSUE TITLE
When running the colab code, the visualization is not ideal

### ISSUE THREAD

**Issue by zzy994491827** [amyxlase/relpose-plus-plus#15]
# Load pretrained weights
model, args = get_model(
    model_dir="/content/relposepp_masked/",
    num_images=8,
    device="cuda"
)

Loading checkpoint ckpt_000800000.pth
Missing keys: ['feature_extractor.feature_positional_encoding.pos_table_1']
Unexpected keys: []

**Comment by zzy994491827** [comment]
# TODO: For each image, please select a bounding box using the interactive tool below.
# The tool should take less than a minute to load.
# If it is taking longer, try increasing the downscale factor below or creating a new runtime.
# Information about drawn bounding boxes will appear below the display.
# If you would like to redo a bounding box, select it and press 'Erase Active Shape' in the top right.

DOWNSCALE_FACTOR = 10
s = select_bbox(IMAGE_DIR, DOWNSCALE_FACTOR)
s.show_image()

TypeError                                 Traceback (most recent call last)
[<ipython-input-35-fee38198e22d>](https://localhost:8080/#) in <cell line: 9>()
      7 DOWNSCALE_FACTOR = 10
      8 s = select_bbox(IMAGE_DIR, DOWNSCALE_FACTOR)
----> 9 s.show_image()

[<ipython-input-34-6420c729b540>](https://localhost:8080/#) in show_image(self)
    105 
    106   def show_image(self):
--> 107       app.run_server(debug=False,mode='inline')

[/usr/local/lib/python3.10/dist-packages/jupyter_dash/jupyter_app.py](https://localhost:8080/#) in run_server(self, mode, width, height, inline_exceptions, **kwargs)
    220         old_server = self._server_threads.get((host, port))
    221         if old_server:
--> 222             old_server.kill()
    223             old_server.join()
    224             del self._server_threads[(host, port)]

[/usr/local/lib/python3.10/dist-packages/jupyter_dash/_stoppable_thread.py](https://localhost:8080/#) in kill(self)
     14         thread_id = self.get_id()
     15         res = ctypes.pythonapi.PyThreadState_SetAsyncExc(
---> 16             ctypes.c_long(thread_id), ctypes.py_object(SystemExit)
     17         )
     18         if res == 0:

TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by zzy994491827** [comment]
DOWNSCALE_FACTOR = 10
s = select_bbox(IMAGE_DIR, DOWNSCALE_FACTOR)
s.show_image()

TypeError                                 Traceback (most recent call last)
[<ipython-input-35-fee38198e22d>](https://localhost:8080/#) in <cell line: 9>()
      7 DOWNSCALE_FACTOR = 10
      8 s = select_bbox(IMAGE_DIR, DOWNSCALE_FACTOR)
----> 9 s.show_image()

2 frames
[<ipython-input-34-6420c729b540>](https://localhost:8080/#) in show_image(self)
    105 
    106   def show_image(self):
--> 107       app.run_server(debug=False,mode='inline')

[/usr/local/lib/python3.10/dist-packages/jupyter_dash/jupyter_app.py](https://localhost:8080/#) in run_server(self, mode, width, height, inline_exceptions, **kwargs)
    220         old_server = self._server_threads.get((host, port))
    221         if old_server:
--> 222             old_server.kill()
    223             old_server.join()
    224             del self._server_threads[(host, port)]

[/usr/local/lib/python3.10/dist-packages/jupyter_dash/_stoppable_thread.py](https://localhost:8080/#) in kill(self)
     14         thread_id = self.get_id()
     15         res = ctypes.pythonapi.PyThreadState_SetAsyncExc(
---> 16             ctypes.c_long(thread_id), ctypes.py_object(SystemExit)
     17         )
     18         if res == 0:

TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by jasonyzhang** [comment]
Can you post a saved version of your colab to replicate this issue?
