### ISSUE TITLE
access 3D object pose via 3D cuboid around the object or sparse point clouds for novel objects

### ISSUE THREAD

**Issue by monajalal** [amyxlase/relpose-plus-plus#2]
Thanks a lot for sharing your code. Are you able to add a demo code that showcases how to retrieve the 3D cuboid/bounding box around the object as well? I saw you retrieved the camera poses for the robot in the notebook. Thank you.

**Comment by jasonyzhang** [comment]
Hi,

Our code does not support recovering a 3D bounding box. There is a demo with recovering camera poses for the robot, but that does not require a bounding box or cuboid.

Best,
Jason
