### ISSUE TITLE
Failed to predict camera poses

### ISSUE THREAD

**Issue by gitformer** [amyxlase/relpose-plus-plus#5]
Hi there,

I tried the relposepp_masked checkpoint to predict camera poses of some images with masks: [images.zip](https://github.com/amyxlase/relpose-plus-plus/files/11884944/images.zip)

The input images are:
![input](https://github.com/amyxlase/relpose-plus-plus/assets/97229157/4eef7a00-c82d-4e8c-8581-143855d6ecb0)

However, the result seems not correct:
![result](https://github.com/amyxlase/relpose-plus-plus/assets/97229157/37cec7d2-6801-4660-be80-8585dc76d571)

I'd like to know if I have made any mistake on testing the code? Thanks a lot!

**Comment by jasonyzhang** [comment]
Hi,

Our model was trained on real images, so it probably will not work well on synthetically rendered models. You may need to retrain the model if you wish to use it on synthetic images.
